export const galleryItems = [
  {
    id: 1,
    type: "image",
    src: "/assets/1.jpg",
    title: "Photobooth at BTM Mall",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 2,
    type: "image",
    src: "/assets/2.jpg",
    title: "Photobooth at BTM Mall",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 3,
    type: "image",
    src: "/assets/3.jpg",
    title: "Photobooth at BTM Mall",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 4,
    type: "image",
    src: "/assets/4.jpg",
    title: "Photobooth at BTM Mall",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 5,
    type: "image",
    src: "/assets/5.jpg",
    title: "Photobooth at Blok M",
    description: "",
    category: "jakarta",
    subCategory: "jakarta-selatan",
  },
  {
    id: 6,
    type: "image",
    src: "/assets/6.jpg",
    title: "Photobooth at Blok M",
    description: "",
    category: "jakarta",
    subCategory: "jakarta-selatan",
  },
  {
    id: 7,
    type: "image",
    src: "/assets/7.jpg",
    title: "Photobooth at Blok M",
    description: "",
    category: "jakarta",
    subCategory: "jakarta-selatan",
  },
  {
    id: 8,
    type: "image",
    src: "/assets/8.jpg",
    title: "Photobooth at Blok M",
    description: "",
    category: "jakarta",
    subCategory: "jakarta-selatan",
  },
  {
    id: 9,
    type: "image",
    src: "/assets/9.jpg",
    title: "Photobooth at Blok M",
    description: "",
    category: "jakarta",
    subCategory: "jakarta-selatan",
  },
  {
    id: 10,
    type: "image",
    src: "/assets/10.jpg",
    title: "Photobooth at Blok M",
    description: "",
    category: "jakarta",
    subCategory: "jakarta-selatan",
  },
  {
    id: 11,
    type: "image",
    src: "/assets/11.jpg",
    title: "Photobooth at Blok M",
    description: "",
    category: "jakarta",
    subCategory: "jakarta-selatan",
  },
  {
    id: 12,
    type: "image",
    src: "/assets/12.jpg",
    title: "Photobooth at Blok M",
    description: "",
    category: "jakarta",
    subCategory: "jakarta-selatan",
  },
  {
    id: 13,
    type: "image",
    src: "/assets/13.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 14,
    type: "image",
    src: "/assets/14.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 15,
    type: "image",
    src: "/assets/15.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 16,
    type: "image",
    src: "/assets/16.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 17,
    type: "image",
    src: "/assets/17.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 18,
    type: "image",
    src: "/assets/18.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 19,
    type: "image",
    src: "/assets/19.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 20,
    type: "image",
    src: "/assets/20.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 21,
    type: "image",
    src: "/assets/21.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 22,
    type: "image",
    src: "/assets/22.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 23,
    type: "image",
    src: "/assets/23.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 24,
    type: "image",
    src: "/assets/24.jpg",
    title: "At Sequoia Coffee And Space",
    description: "",
    category: "bogor",
    subCategory: "bogor-tengah",
  },
  {
    id: 25,
    type: "image",
    src: "/assets/Burger.avif",
    title: "At The Rock Burger Timoho",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 26,
    type: "image",
    src: "/assets/Burger 2.avif",
    title: "At The Rock Burger Timoho",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 27,
    type: "image",
    src: "/assets/Gelato.avif",
    title: "At Tempo Gelato",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 28,
    type: "image",
    src: "/assets/Jogja Heritage.avif",
    title: "At Jogja Heritage",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 29,
    type: "image",
    src: "/assets/Jogja Heritage 2.avif",
    title: "At Museum Sonobudoyo Unit",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 30,
    type: "image",
    src: "/assets/Jogja Heritage 3.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 31,
    type: "image",
    src: "/assets/Jogja Heritage 4.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 32,
    type: "image",
    src: "/assets/Jogja Heritage 5.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 33,
    type: "image",
    src: "/assets/Jogja Heritage 6.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 34,
    type: "image",
    src: "/assets/Jogja Heritage 7.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 35,
    type: "image",
    src: "/assets/Jogja Heritage 8.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 36,
    type: "image",
    src: "/assets/Jogja Heritage 9.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 37,
    type: "image",
    src: "/assets/Jogja Heritage 10.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 38,
    type: "image",
    src: "/assets/Jogja Heritage 11.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 39,
    type: "image",
    src: "/assets/Jogja Heritage 12.avif",
    title: "At Museum Sonobudoyo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 40,
    type: "image",
    src: "/assets/KANO MARITIM BAROS.avif",
    title: "At Kano Maritim Baros",
    description: "",
    category: "yogyakarta",
    subCategory: "bantul",
  },
  {
    id: 41,
    type: "image",
    src: "/assets/Keraton Yogyakarta.avif",
    title: "At Kraton Ngayogyakarta Hadiningrat",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 42,
    type: "image",
    src: "/assets/L'Union Pizza.avif",
    title: "At L'Union Pizza",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 43,
    type: "image",
    src: "/assets/Malioboro 2.avif",
    title: "At Malioboro",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 44,
    type: "image",
    src: "/assets/Pasar Ngasem.avif",
    title: "At Pasar Ngasem",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 45,
    type: "image",
    src: "/assets/Pasar Beringharjo Yogyakarta.avif",
    title: "At Pasar Beringharjo",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 46,
    type: "image",
    src: "/assets/Pasar prawirotaman.avif",
    title: "At Pasar Prawirotaman",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 47,
    type: "image",
    src: "/assets/PICTNIQ.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 48,
    type: "image",
    src: "/assets/PICTNIQ 2.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 49,
    type: "image",
    src: "/assets/PICTNIQ 3.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 50,
    type: "image",
    src: "/assets/PICTNIQ 4.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 51,
    type: "image",
    src: "/assets/PICTNIQ 5.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 52,
    type: "image",
    src: "/assets/PICTNIQ 6.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 53,
    type: "image",
    src: "/assets/PICTNIQ 7.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 54,
    type: "image",
    src: "/assets/PICTNIQ 8.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 55,
    type: "image",
    src: "/assets/PICTNIQ 9.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 56,
    type: "image",
    src: "/assets/PICTNIQ 10.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 57,
    type: "image",
    src: "/assets/PICTNIQ 11.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 58,
    type: "image",
    src: "/assets/PICTNIQ 12.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 59,
    type: "image",
    src: "/assets/PICTNIQ 13.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 60,
    type: "image",
    src: "/assets/PICTNIQ 14.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 61,
    type: "image",
    src: "/assets/PICTNIQ 15.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 62,
    type: "image",
    src: "/assets/PICTNIQ 16.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 63,
    type: "image",
    src: "/assets/PICTNIQ 17.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 64,
    type: "image",
    src: "/assets/PICTNIQ 18.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 65,
    type: "image",
    src: "/assets/PICTNIQ 19.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 66,
    type: "image",
    src: "/assets/PICTNIQ 20.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 67,
    type: "image",
    src: "/assets/PICTNIQ 21.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 68,
    type: "image",
    src: "/assets/PICTNIQ 22.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 69,
    type: "image",
    src: "/assets/PICTNIQ 23.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 70,
    type: "image",
    src: "/assets/PICTNIQ 24.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 71,
    type: "image",
    src: "/assets/PICTNIQ 25.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 72,
    type: "image",
    src: "/assets/PICTNIQ 26.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 73,
    type: "image",
    src: "/assets/PICTNIQ 27.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 74,
    type: "image",
    src: "/assets/PICTNIQ 28.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 75,
    type: "image",
    src: "/assets/PICTNIQ 29.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 76,
    type: "image",
    src: "/assets/PICTNIQ 30.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 77,
    type: "image",
    src: "/assets/PICTNIQ 31.avif",
    title: "At PICTNIQ",
    description: "",
    category: "yogyakarta",
    subCategory: "kidul",
  },
  {
    id: 78,
    type: "image",
    src: "/assets/Taman Sari.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 79,
    type: "image",
    src: "/assets/Taman Sari 2.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 80,
    type: "image",
    src: "/assets/Taman Sari 3.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 81,
    type: "image",
    src: "/assets/Taman Sari 4.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 82,
    type: "image",
    src: "/assets/Taman Sari 5.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 83,
    type: "image",
    src: "/assets/Taman Sari 6.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 84,
    type: "image",
    src: "/assets/Taman Sari 7.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 85,
    type: "image",
    src: "/assets/Taman Sari 8.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 86,
    type: "image",
    src: "/assets/Taman Sari 9.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 87,
    type: "image",
    src: "/assets/Taman Sari 10.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
  {
    id: 88,
    type: "image",
    src: "/assets/Taman Sari 11.avif",
    title: "At Taman Sari",
    description: "",
    category: "yogyakarta",
    subCategory: "yogya-kota",
  },
]

// Struktur kategori hierarkis
export const categoryStructure = {
  all: { label: "All", parent: null },
  jakarta: {
    label: "Jakarta",
    parent: null,
    children: ["jakarta-pusat", "jakarta-selatan", "jakarta-utara", "jakarta-timur", "jakarta-barat"],
  },
  yogyakarta: {
    label: "Yogyakarta",
    parent: null,
    children: ["yogya-kota", "sleman", "bantul", "kidul"],
  },
  bogor: {
    label: "Bogor",
    parent: null,
    children: ["bogor-tengah", "bogor-barat", "bogor-timur", "puncak", "cianjur"],
  },
  // Sub-categories Jakarta
  "jakarta-pusat": { label: "Jakarta Pusat", parent: "jakarta" },
  "jakarta-selatan": { label: "Jakarta Selatan", parent: "jakarta" },
  "jakarta-utara": { label: "Jakarta Utara", parent: "jakarta" },
  "jakarta-timur": { label: "Jakarta Timur", parent: "jakarta" },
  "jakarta-barat": { label: "Jakarta Barat", parent: "jakarta" },
  // Sub-categories Yogyakarta
  "yogya-kota": { label: "Kota Yogyakarta", parent: "yogyakarta" },
  sleman: { label: "Sleman", parent: "yogyakarta" },
  bantul: { label: "Bantul", parent: "yogyakarta" },
  kidul: { label: "Gunung Kidul", parent: "yogyakarta" },
  // Sub-categories Bogor
  "bogor-tengah": { label: "Bogor Tengah", parent: "bogor" },
  "bogor-barat": { label: "Bogor Barat", parent: "bogor" },
  "bogor-timur": { label: "Bogor Timur", parent: "bogor" },
  puncak: { label: "Puncak", parent: "bogor" },
  cianjur: { label: "Cianjur", parent: "bogor" },
}